"""Added many tables

Revision ID: 8423032f2cc7
Revises: 
Create Date: 2023-09-14 12:42:27.430840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8423032f2cc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbr', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_abbr'), 'classes', ['abbr'], unique=False)
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbr', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_abbr'), 'sources', ['abbr'], unique=False)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=False)
    op.create_table('spell_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spell_attributes_id'), 'spell_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_spell_attributes_name'), 'spell_attributes', ['name'], unique=False)
    op.create_table('spell_casting_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spell_casting_times_id'), 'spell_casting_times', ['id'], unique=False)
    op.create_index(op.f('ix_spell_casting_times_name'), 'spell_casting_times', ['name'], unique=False)
    op.create_table('spell_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbr', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spell_components_abbr'), 'spell_components', ['abbr'], unique=False)
    op.create_index(op.f('ix_spell_components_id'), 'spell_components', ['id'], unique=False)
    op.create_index(op.f('ix_spell_components_name'), 'spell_components', ['name'], unique=False)
    op.create_table('spell_durations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spell_durations_id'), 'spell_durations', ['id'], unique=False)
    op.create_index(op.f('ix_spell_durations_name'), 'spell_durations', ['name'], unique=False)
    op.create_table('spell_resistances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spell_resistances_id'), 'spell_resistances', ['id'], unique=False)
    op.create_index(op.f('ix_spell_resistances_name'), 'spell_resistances', ['name'], unique=False)
    op.create_table('spell_schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spell_schools_id'), 'spell_schools', ['id'], unique=False)
    op.create_index(op.f('ix_spell_schools_name'), 'spell_schools', ['name'], unique=False)
    op.create_table('spell_class_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spell_class_levels_id'), 'spell_class_levels', ['id'], unique=False)
    op.create_table('spell_subschools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['spell_schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spell_subschools_id'), 'spell_subschools', ['id'], unique=False)
    op.create_index(op.f('ix_spell_subschools_name'), 'spell_subschools', ['name'], unique=True)
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('casting_time_id', sa.Integer(), nullable=False),
    sa.Column('spell_resistance_id', sa.Integer(), nullable=False),
    sa.Column('casting_range', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('saving_throw', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('material_components', sa.String(), nullable=False),
    sa.Column('duration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['casting_time_id'], ['spell_schools.id'], ),
    sa.ForeignKeyConstraint(['duration_id'], ['spell_durations.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['spell_schools.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['spell_resistance_id'], ['spell_schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spells_casting_range'), 'spells', ['casting_range'], unique=False)
    op.create_index(op.f('ix_spells_description'), 'spells', ['description'], unique=False)
    op.create_index(op.f('ix_spells_id'), 'spells', ['id'], unique=False)
    op.create_index(op.f('ix_spells_material_components'), 'spells', ['material_components'], unique=False)
    op.create_index(op.f('ix_spells_name'), 'spells', ['name'], unique=False)
    op.create_index(op.f('ix_spells_saving_throw'), 'spells', ['saving_throw'], unique=False)
    op.create_index(op.f('ix_spells_target'), 'spells', ['target'], unique=False)
    op.create_table('spell_to_spell_attributes',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('spell_attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spell_attribute_id'], ['spell_attributes.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], ),
    sa.PrimaryKeyConstraint('spell_id', 'spell_attribute_id')
    )
    op.create_table('spell_to_spell_class_levels',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('spell_class_level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spell_class_level_id'], ['spell_class_levels.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], ),
    sa.PrimaryKeyConstraint('spell_id', 'spell_class_level_id')
    )
    op.create_table('spell_to_spell_components',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('spell_component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spell_component_id'], ['spell_components.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], ),
    sa.PrimaryKeyConstraint('spell_id', 'spell_component_id')
    )
    op.create_table('spell_to_spell_subschools',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('spell_subschool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], ),
    sa.ForeignKeyConstraint(['spell_subschool_id'], ['spell_subschools.id'], ),
    sa.PrimaryKeyConstraint('spell_id', 'spell_subschool_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spell_to_spell_subschools')
    op.drop_table('spell_to_spell_components')
    op.drop_table('spell_to_spell_class_levels')
    op.drop_table('spell_to_spell_attributes')
    op.drop_index(op.f('ix_spells_target'), table_name='spells')
    op.drop_index(op.f('ix_spells_saving_throw'), table_name='spells')
    op.drop_index(op.f('ix_spells_name'), table_name='spells')
    op.drop_index(op.f('ix_spells_material_components'), table_name='spells')
    op.drop_index(op.f('ix_spells_id'), table_name='spells')
    op.drop_index(op.f('ix_spells_description'), table_name='spells')
    op.drop_index(op.f('ix_spells_casting_range'), table_name='spells')
    op.drop_table('spells')
    op.drop_index(op.f('ix_spell_subschools_name'), table_name='spell_subschools')
    op.drop_index(op.f('ix_spell_subschools_id'), table_name='spell_subschools')
    op.drop_table('spell_subschools')
    op.drop_index(op.f('ix_spell_class_levels_id'), table_name='spell_class_levels')
    op.drop_table('spell_class_levels')
    op.drop_index(op.f('ix_spell_schools_name'), table_name='spell_schools')
    op.drop_index(op.f('ix_spell_schools_id'), table_name='spell_schools')
    op.drop_table('spell_schools')
    op.drop_index(op.f('ix_spell_resistances_name'), table_name='spell_resistances')
    op.drop_index(op.f('ix_spell_resistances_id'), table_name='spell_resistances')
    op.drop_table('spell_resistances')
    op.drop_index(op.f('ix_spell_durations_name'), table_name='spell_durations')
    op.drop_index(op.f('ix_spell_durations_id'), table_name='spell_durations')
    op.drop_table('spell_durations')
    op.drop_index(op.f('ix_spell_components_name'), table_name='spell_components')
    op.drop_index(op.f('ix_spell_components_id'), table_name='spell_components')
    op.drop_index(op.f('ix_spell_components_abbr'), table_name='spell_components')
    op.drop_table('spell_components')
    op.drop_index(op.f('ix_spell_casting_times_name'), table_name='spell_casting_times')
    op.drop_index(op.f('ix_spell_casting_times_id'), table_name='spell_casting_times')
    op.drop_table('spell_casting_times')
    op.drop_index(op.f('ix_spell_attributes_name'), table_name='spell_attributes')
    op.drop_index(op.f('ix_spell_attributes_id'), table_name='spell_attributes')
    op.drop_table('spell_attributes')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_abbr'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_abbr'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
